sudo: required
services: 
    -docker
before_install:
    - docker build  -t sushilpanwar091/dicker-react -f Dockerfile.dev .
script:
    - docker run sushilpanwar091/dicker-react npm run test -- --coverage